### ISSUE TITLE
How to use instead of Rynchodons version?

### ISSUE THREAD

**Issue by MrDibbley** [ShawnTheShadow/Autopilot#2]
Do i need to get your plugin loader / manager to compile to get SE launching?

Thanks

**Comment by ShawnTheShadow** [comment]
I recommend using the one i supplied, as it has needed code changes to work with the latest SE codebase. 
Just change Author in each one to ShawnTheShadow to update to my repo.
Sorry for the really late response, Github doesn't send notifications when an issue is added.
