### ISSUE TITLE
Instaling Amrs

### ISSUE THREAD

**Issue by Mugiwaxar** [ShawnTheShadow/Autopilot#3]
Hello,
I just want to use ARMS, like I alway used it, but I need some help
Pluging manager is installed and configured with ShawnTheShadow author
Arms plugins is correctly downloaded and loaded when SE start
Now, what I have to do?

**Comment by ShawnTheShadow** [comment]
First run the installer from https://github.com/ShawnTheShadow/SpaceEngineersPluginLoader/releases once you have that installed, run the plugin loader, the one originally supplied by Rynchodon is broken on latest update. Then once you've run the plugin loader, click in the boxes that say "Rynchodon" and change to "ShawnTheShadow" and it should automatically download the updated files.

**Comment by Mugiwaxar** [comment]
Ok, it's done
And next, where I can find the mod?
Thanks for your help :)

**Comment by ShawnTheShadow** [comment]
Did you open the Plugin Loader after?

**Comment by Mugiwaxar** [comment]
I have to use "-plugin ..\SpaceEngineersPluginLoader\PluginLoader.dll" command cause if I click "Launch SE and SEPL", the game crash
![sans titre](https://user-images.githubusercontent.com/4124999/35405647-23379612-0207-11e8-8ec7-414e09107d03.png)

**Comment by ShawnTheShadow** [comment]
Strange, i use the plugin loader in my game, but the -plugin works also. You'll also need the mod files, which can be compiled from the source, but i didn't think about making a packed version. Of course, i wasn't expecting the original author to remove his mod so soon.

**Comment by Mugiwaxar** [comment]
Any other way than compile?
Too complicated, and I don't have Visual Studio
:(

**Comment by ShawnTheShadow** [comment]
I've updated the release page, it now has a packed version of the mod files, just unpack into a new folder named ARMS in your mod directory.

**Comment by Mugiwaxar** [comment]
You are so nice!
Thanks a lot

**Comment by Mugiwaxar** [comment]
How to make it allowed in multiplayer ?

**Comment by ShawnTheShadow** [comment]
Would need the mod re-uploaded to Steam, but i haven't gotten permission to do so. For the script side, same with the plugin loader, run the DS with -plugin or use the plugin loader.

**Comment by Mugiwaxar** [comment]
Ok
I'll try in singleplayer
Thanks for all! :)

**Comment by ShawnTheShadow** [comment]
no problem

**Comment by Mugiwaxar** [comment]
Hum...
When I set the command "g EarthStation"
Nothing appen

**Comment by ShawnTheShadow** [comment]
What is the full command? What are you going to do with the Grid EartStation?

**Comment by Mugiwaxar** [comment]
Go to

**Comment by ShawnTheShadow** [comment]
So you'll need to use a group of commands to tell it to move to the grid. 
Like for mine 
```
U Connector
C GPS coordinates
L Connector
B Connector Ore In
G Mars Station
Exit
```

**Comment by Mugiwaxar** [comment]
The guide was deleted or we can find it somewhere?

**Comment by ShawnTheShadow** [comment]
Original is gone, but it's on the repo [https://github.com/ShawnTheShadow/Autopilot/blob/master/Steam%20Description/Autopilot%20Navigation.txt](url)

**Comment by Mugiwaxar** [comment]
My ship travel Backward :D

**Comment by ShawnTheShadow** [comment]
Yeah that is easily fixed, N FrontCamera (or whatever else facing forward) then facemove before the movement commands

**Comment by Mugiwaxar** [comment]
Ok, many thanks
Hmm, first try, Autopilot have crashed my ship on a planet
Have to retry

**Comment by ShawnTheShadow** [comment]
You have no idea how many times that's happened to me, takes practice to get right

**Comment by ShawnTheShadow** [comment]
Mod uploaded approved by mod author http://steamcommunity.com/sharedfiles/filedetails/?id=1286147283
