### ISSUE TITLE
log reports no available releases when SE launched from loader?

### ISSUE THREAD

**Issue by MrDibbley** [ShawnTheShadow/Autopilot#4]
`{11:23:06.359}{Loader}{.ctor}{199}{SEPL version: v1.1.6.0}
{11:23:06.364}{DownloadProgress}{.ctor}{55}{entered}
{11:23:06.364}{Loader}{Init}{290}{Opening download screen}
{11:23:06.367}{DownloadProgress}{beginAction}{37}{opening download screen}
{11:23:06.402}{PluginData}{Load}{118}{Loading config}
{11:23:06.405}{PluginData}{Load}{131}{Loading downloads}
{11:23:06.407}{Loader}{UpdatePlugin}{341}{Updating plugins}
{11:23:06.411}{Loader}{UpdatePlugin}{374}{plugin: ShawnTheShadow.SpaceEngineersPluginLoader}
{11:23:07.221}{GitHubClient}{Update}{310}{ERROR: No available releases}
{11:23:07.221}{Loader}{UpdatePlugin}{374}{plugin: ShawnTheShadow.Autopilot}
{11:23:07.344}{GitHubClient}{Update}{310}{ERROR: No available releases}
{11:23:07.356}{DownloadProgress}{endAction}{43}{closing download screen}
{11:23:07.356}{Loader}{CheckTask}{325}{Finished task, loading plugins}
{11:23:07.357}{Loader}{LoadPlugin}{410}{ShawnTheShadow.SpaceEngineersPluginLoader was not downloaded, cannot be loaded}
{11:23:07.357}{Loader}{LoadPlugin}{410}{ShawnTheShadow.Autopilot was not downloaded, cannot be loaded}
{11:24:31.613}{Loader}{Robocopy}{254}{starting robocopy}`

**Comment by ShawnTheShadow** [comment]
Oh i forgot about that, i had the releases set as "pre-release" forgot to switch it over. Try it again.

**Comment by MrDibbley** [comment]
Thats seem to fixed that issue, both now download OK, now if i load a saved game it reports ARMS needs load-arms to run ? 

Thanks

**Comment by ShawnTheShadow** [comment]
Seems the latest update broke he script, I'll have to figure out what was changed.
